export const ORGAOS_EXPEDIDORES = [
  'SECRETARIA DE SEGURANÇA PÚBLICA',
  'ORDEM DOS ADVOGADOS DO BRASIL',
  'MINISTÉRIO DA AERONÁUTICA',
  'MINISTÉRIO DO EXÉRCITO',
  'MINISTÉRIO DA MARINHA',
  'POLICIA FEDERAL (DPMAF - DELEGACIA DE POLÍCIA MARÍTIMA, AÉREA E DE FRONTEIRA)',
  'CONSELHO REGIONAL DE ADMINISTRAÇÃO',
  'CONSELHO REGIONAL DE ASSISTENCIA SOCIAL',
  'CONSELHO REGIONAL DE BIBLIOTECONOMIA',
  'CONSELHO REGIONAL DE CONTABILIDADE',
  'CONSELHO REGIONAL DE CORRETORES DE IMÓVEIS',
  'CONSELHO REGIONAL DE ECONOMIA',
  'CONSELHO REGIONAL DE ENFERMAGEM',
  'CONSELHO REGIONAL DE ADMINISTRAÇÃO',
  'CONSELHO REGIONAL DE ENGENHARIA, ARQUITETURA E AGRONOMIA',
  'CONSELHO REGIONAL DE ESTATÍSTICA',
  'CONSELHO REGIONAL DE FARMÁCIA',
  'CONSELHO REGIONAL DE FISIOTERAPIA E TERAPIA OCUPACIONAL',
  'CONSELHO REGIONAL DE MEDICINA',
  'CONSELHO REGIONAL DE MEDICINA VETERINÁRIA',
  'ORDEM DOS MÚSICOS DO BRASIL',
  'CONSELHO REGIONAL DE NUTRIÇÃO',
  'CONSELHO REGIONAL DE ODONTOLOGIA',
  'CONSELHO REGIONAL DE PROFISSIONAIS DE RELAÇÕES PÚBLICAS',
  'CONSELHO REGIONAL DE PSICOLOGIA',
  'CONSELHO REGIONAL DE QUÍMICA',
  'CONSELHO REGIONAL DE REPRESENTANTES COMERCIAIS',
  'CONSELHO REGIONAL DE BIOLOGIA',
  'CONSELHO REGIONAL DE FONOAUDIOLOGIA',
  'CONSELHO REGIONAL DE SERVIÇO SOCIAL',
  'CONSELHO REGIONAL DE TÉCNICOS EM RADIOLOGIA',
  'DEPARTAMENTO DE TRÂNSITO',
  'POLÍCIA MILITAR',
  'CORPO DE BOMEIROS',
  'INSTITUO BRASILEIRO DE ATUÁRIOS',
  'SECRETARIA OU COORDENAÇÃO ESTADUAL DA JUSTIÇA E DEFESA SOCIAL',
  'SECRETARIA OU COORDENAÇÃO MUNICIPAL DA DEFESA SOCIAL',
  'DOCUMENTO EXPEDIDO NO EXTERIOR',
  'OUTROS',
];

export const NACIONALIDADES = [
  'BRASILEIRA',
  'NATURALIZADO BRASILEIRO',
  'BRASILEIRO NASCIDO NO EXTERIOR',
  'ESTRANGEIRA',
];

export const ESTADOS_CIVIS = [
  'SOLTEIRO',
  'CASADO',
  'DIVORCIADO',
  'VIÚVO',
  'UNIÃO ESTÁVEL',
];

export const ESCOLARIDADE = [
  'Sem escolaridade',
  'Ensino fundamental incompleto',
  'Ensino fundamental completo',
  'Ensino médio incompleto',
  'Ensino médio completo',
  'Superior incompleto',
  'Superior completo',
  'Pós- graduação incompleta',
  'Pós-graduação completa	',
];


export const PRODUTO_NAO_ENTREGUE_TIPO = [
  'Produto não entregue',
  'Produto divergente do contratado',
];															


export const dataRegex = /(^(((0[1-9]|1[0-9]|2[0-8])[/](0[1-9]|1[012]))|((29|30|31)[/](0[13578]|1[02]))|((29|30)[/](0[4,6,9]|11)))[/](19|[2-9][0-9])\d\d$)|(^29[/]02[/](19|[2-9][0-9])(00|04|08|12|16|20|24|28|32|36|40|44|48|52|56|60|64|68|72|76|80|84|88|92|96)$)/;
